# Basic no-TLS config for the embedded gateway
proxyconfig:
  ## Self-signed with locally generated CA Root and certs  
  bindurl: https://localhost:443
  externalurl: https://localhost
  redirecturls:
      - http://localhost
  tlsconfig:
      selfsigned:
          hostnames:
              - localhost
  
## Cells non-interactive install  
internalurl: https://localhost:443
dbconnectiontype: tcp
dbtcphostname: mysql
dbtcpport: 3306
dbtcpname: cells
dbtcpuser: pydio
dbtcppassword: cells
dsname: pydiods1
dsport: 41850
dsfolder: /data
externalmicro: 0
externalgateway: 42568
externalwebsocket: 42402
externalfrontfplugins: 45434
externaldav: 43773
externalwopi: 35205
externaldex: 44771
externaldexid: cells-front
externaldexsecret: cells-front
frontendlogin: admin
frontendpassword: admin
frontendrepeatpassword: admin
frontendapplicationtitle: Pydio Cells
frontenddefaultlanguage: en
licenserequired: false
