proxyconfig:
  ## Basic no-TLS config
  # You should replace "localhost" with your public IP or the corresponding domain name
  # if your want your instance to be reachable from the internet
  bindurl: http://localhost:80
  externalurl: http://localhost

  ### Self-signed with locally generated CA Root and certs  
  ## This configuration is usefull for testing purpose if you have an internet facing ip
  ## or can be used behind a reverse proxy in "insecure_skip_verify" (or equivalent) mode
  ## or by installing the locally generated Root CA in your reverse proxy
  ## repl cells.example.com by your IP address or the corresponding DNS regitered domain name.
  #bindurl: https://cells.example.com:443
  #externalurl: https://cells.example.com
  #redirecturls:
  #    - http://cells.example.com
  #tlsconfig:
  #    selfsigned:
  #        hostnames:
  #            - cells.example.com

  ### Using provided certificates
  ## Use this mode if you want to use certificates that are not managed by cells
  ## Note that we reference the passed paths rather than copying the files:
  ## you must mount a valume that contain this files for them to be found.
  #bindurl: https://cells.example.com:443
  #externalurl: https://cells.example.com
  #redirecturls:
  #    - http://cells.example.com
  #tlsconfig:
  #  certificate:
  #    certfile: /var/cells/certs/cells.example.com-cert.pem
  #    keyfile: /var/cells/certs/cells.example.com-key.pem

  ### Using Let's Encrypt automated certificate generation
  ## Cells can tranparently manage creation and update of your certificates thanks to Let's Encrypt.
  ## *WARNING*: let's encrypt has quite restrictive rate limit policies to prevent misuse.
  ## So before turning the Staging CA flag off, insure that:
  ## - your setup works and you can install cells until login screen with the fake LE certificate 
  ## - you have mounted the corresponding folder in a persitent volume: even with a working setup, 
  ##   generating your certificates from scratch more than a few time will have you hit the limit and 
  ##   your domain name will be blacklisted for a while.
  #bindurl: https://cells.example.com:443
  #externalurl: https://cells.example.com
  #redirecturls:
  #    - http://cells.example.com
  #tlsconfig:
  #  letsencrypt:
  #    email: sofia@example.com
  #    accepteula: true
  #    stagingca: true
