version: "3"

services:

  cells:
    image: pydio/cells:latest
    restart: always
    ports: ["8080:8080"]
    environment:
      - CELLS_INSTALL_YAML=/pydio/config/install.yml
    volumes: 
      - cellsdir:/var/cells
      - ./install-conf.yml:/pydio/config/install.yml:ro
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMe!
      MYSQL_DATABASE: cells
      MYSQL_USER: pydio
      MYSQL_PASSWORD: ChangeMe!
    volumes:
      - mysqldir:/var/lib/mysql
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]

volumes:
  cellsdir: {}
  mysqldir: {}
