version: "3"

services:

  cells:
    image: pydio/cells:latest
    restart: always
    ports: ["80:80", "443:443"]
    environment:
      - CELLS_INSTALL_YAML=/pydio/config/install.yml
      - PYDIO_EXIT_AFTER_INSTALL=true
    volumes: 
      - "workingdir:/var/cells"
      - "datadir:/data"
      - "./config:/pydio/config"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cells
      MYSQL_DATABASE: cells
      MYSQL_USER: pydio
      MYSQL_PASSWORD: cells
    volumes:
      - "mysqldir:/var/lib/mysql"
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
      ]

volumes:
  workingdir: {}
  datadir: {}
  mysqldir: {}
