version: "3.7"

services:
  reverse:
    image: traefik:2.3
    ports: [80:80]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --providers.docker
      - --api
      - --entrypoints.web.address=:80
    labels:
      - traefik.http.routers.reverse.service=api@internal
      - traefik.http.routers.reverse.rule=PathPrefix(`/api`)||PathPrefix(`/dashboard`)
      - traefik.http.routers.reverse.entrypoints=web

  cells:
    image: pydio/cells:pre-release
    restart: unless-stopped
    expose: [8080]
    environment:
      - CELLS_INSTALL_YAML=/pydio/config/install.yml
      - CELLS_NO_TLS=1
    volumes: 
      - cellsdir:/var/cells
      - ./install-conf.yml:/pydio/config/install.yml:ro
    labels:
      - traefik.http.routers.cells.rule=Host(`localhost`)
      - traefik.http.routers.cells.entrypoints=web

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment: [MYSQL_DATABASE=cells, MYSQL_USER=pydio, MYSQL_ROOT_PASSWORD=ChangeMe!, MYSQL_PASSWORD=ChangeMe!]
    volumes: [mysqldir:/var/lib/mysql]
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]

volumes:
  cellsdir: {}
  mysqldir: {}
